import { RouterProvider, createRouter } from '@tanstack/react-router'

// Import the generated route tree (auto-generated by TanStack Router CLI)
import { routeTree } from './routeTree.gen'

const router = createRouter({ routeTree })

// Register router for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

export default function App() {
  return <RouterProvider router={router} />
}